import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: "Nextjs Home Page",
    template: "%s Rafarock"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-cyan-500 p-4'>
          <p>Header</p>
        </header>
        {children}
        <footer className='bg-orange-200 p-4'>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
